// SPDX-License-Identifier: Apache-2.0
// Cross-language parity scenarios for the RM v1 evaluator (I4). Each scenario uses
// only the signed fixtures; the reduced outcome is what TypeScript and Python must
// agree on exactly. Used by scripts/generate-rm-v1-parity.ts and the parity tests.
import { readFileSync } from 'node:fs';
import { createRelianceRequest, loadRelianceProfile } from '../src/reliance/index.js';
import { evaluateRmSlice } from '../src/reliance/rm-v1-slice.js';
import type { JsonObject } from '../src/types.js';
import { catalogWith, manifest, request, URI } from './rm-v1-helpers.js';

export interface ParityScenario {
  readonly id: string;
  readonly targetId: string;
  readonly profile: string;
  readonly activityTime?: string;
  readonly conformity: { readonly requirementId: string; readonly decisionRuleId: string } | null;
}

const GUARDED = { requirementId: 'as-mass-fraction-max-200-mg-per-kg', decisionRuleId: 'guarded-acceptance-expanded-u' };
const D = (value: string) => `https://producer.vc4qi.example/credentials/D${value}`;
export const PARITY_SCENARIOS: readonly ParityScenario[] = [
  { id: 'x178-guarded', targetId: URI.D, profile: 'rm-verifier-1.json', conformity: GUARDED },
  { id: 'x197-guarded', targetId: D('197'), profile: 'rm-verifier-1.json', conformity: GUARDED },
  { id: 'x520-guarded', targetId: D('520'), profile: 'rm-verifier-1.json', conformity: GUARDED },
  { id: 'x197-authorization-only', targetId: D('197'), profile: 'rm-verifier-1.json', conformity: null },
  { id: 'x197-simple-acceptance', targetId: D('197'), profile: 'rm-verifier-1.json',
    conformity: { ...GUARDED, decisionRuleId: 'simple-acceptance' } },
  { id: 'x178-unknown-requirement', targetId: URI.D, profile: 'rm-verifier-1.json',
    conformity: { ...GUARDED, requirementId: 'as-max-100' } },
  { id: 'x178-historical-question', targetId: URI.D, profile: 'rm-verifier-1.json',
    activityTime: '2026-03-01T00:00:00Z', conformity: GUARDED },
  { id: 'x178-two-routes', targetId: URI.D, profile: 'rm-verifier-two-routes-1.json', conformity: GUARDED },
];

const profileFile = (name: string) => loadRelianceProfile(JSON.parse(readFileSync(
  new URL(`../../../bindings/experimental/rm-v1/profiles/${name}`, import.meta.url), 'utf8')) as JsonObject);

/** Evaluate every scenario and reduce each result to its language-independent core. */
export async function parityOutcomes() {
  const scenarios = [];
  for (const scenario of PARITY_SCENARIOS) {
    const profile = profileFile(scenario.profile);
    const base = request({
      targetId: scenario.targetId,
      profile: { id: profile.id, version: profile.version },
      ...(scenario.activityTime ? { activityTime: scenario.activityTime } : {}),
    });
    const { conformity: _default, ...plain } = base;
    const req = createRelianceRequest(scenario.conformity ? { ...plain, conformity: scenario.conformity } : plain);
    const { result } = await evaluateRmSlice(req, catalogWith(), manifest, profile);
    scenarios.push({
      ...scenario,
      outcome: {
        decision: result.decision,
        authorization: result.authorization.map(a => ({ claimId: a.claimId, state: a.state, routeWitnessIds: [...a.routeWitnessIds] })),
        support: result.support.map(s => ({ state: s.state, witnessIds: [...s.witnessIds] })),
        conformity: result.conformity.requested
          ? { requested: true, state: result.conformity.state, execution: result.conformity.execution, reasons: [...result.conformity.reasons] }
          : { requested: false },
        trace: result.trace.filter(t => t.gate >= 4)
          .map(t => ({ gate: t.gate, predicate: t.predicate, state: t.state, execution: t.execution, reason: t.reason })),
      },
    });
  }
  return { description: 'RM v1 evaluator outcomes over the signed fixtures; TypeScript and Python must agree exactly. '
    + 'Generated by packages/core-ts/scripts/generate-rm-v1-parity.ts; do not edit.', scenarios };
}
