// Browser-side selective-disclosure driver for the DCC "share" demo.
//
// Loads the SD-secured base DCC plus the lab key/controller docs (generated by
// packages/core-ts/scripts/gen-sd-dcc-fixtures.ts), and runs deriveSd/verifySd
// live in the browser via @qi-vc/core's generic ecdsa-sd-2023 module. The
// derivation is unkeyed — the holder needs no secret — so this is exactly what a
// credential holder does when composing a presentation for a verifier.

import { deriveSd, verifySd } from '@qi-vc/core/proofs/sd';
import type { JsonObject } from '@qi-vc/core';

import baseCredential from '../../../../examples/calibration/digital-calibration-certificate.sd.json';
import labKey from '../../../../examples/calibration/lab-key.jsonld';
import labController from '../../../../examples/calibration/lab-controller.jsonld';

// Bundled contexts so SD's safe-mode jsonld resolves everything offline.
import credentialsV2 from '../../../../contexts/v1/vendor/credentials-v2.jsonld';
import securityMultikey from '../../../../contexts/v1/vendor/security-multikey-v1.jsonld';
import qiEvidence from '../../../../contexts/v1/qi-evidence-context.jsonld';
import qiCalibration from '../../../../contexts/v1/qi-calibration.jsonld';
import qiCore from '../../../../contexts/v1/qi-core.jsonld';

export const SD_BASE = baseCredential as JsonObject;

const STATIC_DOCS: Record<string, JsonObject> = {
  'https://www.w3.org/ns/credentials/v2': credentialsV2 as JsonObject,
  'https://w3id.org/security/multikey/v1': securityMultikey as JsonObject,
  'https://w3id.org/qi-vc/contexts/v1/qi-evidence-context.jsonld': qiEvidence as JsonObject,
  'https://w3id.org/qi-vc/contexts/v1/qi-calibration.jsonld': qiCalibration as JsonObject,
  'https://w3id.org/qi-vc/contexts/v1/qi-core.jsonld': qiCore as JsonObject,
  [String((labKey as JsonObject).id)]: labKey as JsonObject,
  [String((labController as JsonObject).id)]: labController as JsonObject,
};

// Offline loader: serves bundled contexts + the lab key/controller; refuses
// anything else (mirrors core's strict loader, but browser-safe).
// Exported because trust-registry proof verification needs the same contexts
// (notably qi-core, which defines the registry entry terms).
export async function sdLoader(url: string) {
  const doc = STATIC_DOCS[url];
  if (doc) return { contextUrl: null, document: doc, documentUrl: url };
  throw new Error(`SD loader: refusing to fetch unknown URL: ${url}`);
}

/**
 * A selectively-disclosable field the holder can choose to reveal. `pointer` is
 * the RFC-6901 JSON pointer passed to deriveSd; `readValue` reads the cleartext
 * value from the base credential for the preview.
 */
export interface DisclosableField {
  key: string;
  label: string;
  description: string;
  pointers: string[];
  readValue: (cred: JsonObject) => string;
}

function admin(cred: JsonObject): JsonObject {
  return ((cred.credentialSubject as JsonObject)?.administrativeData as JsonObject) ?? {};
}

export const DISCLOSABLE_FIELDS: DisclosableField[] = [
  {
    key: 'customer',
    label: 'Customer identity',
    description: 'Who commissioned the calibration',
    pointers: ['/credentialSubject/administrativeData/customer'],
    readValue: (c) => {
      const cust = admin(c).customer as JsonObject | undefined;
      return cust ? `${cust.name ?? ''}${cust.location ? `, ${cust.location}` : ''}` : '—';
    },
  },
  {
    key: 'instrument',
    label: 'Instrument serial & manufacturer',
    description: 'Which exact unit was calibrated',
    pointers: [
      '/credentialSubject/administrativeData/items/0/identifications',
      '/credentialSubject/administrativeData/items/0/manufacturer',
    ],
    readValue: (c) => {
      const item = (admin(c).items as JsonObject[] | undefined)?.[0] ?? {};
      const ids = (item.identifications as JsonObject[] | undefined) ?? [];
      const serial = ids.find((i) => i.type === 'serialNumber')?.value;
      const mfr = (item.manufacturer as JsonObject | undefined)?.name;
      return [mfr, serial].filter(Boolean).join(' · ') || '—';
    },
  },
];

export interface DisclosureResult {
  derived: JsonObject;
  verified: boolean;
  error?: string;
}

/**
 * Derive a disclosed subset revealing the chosen fields, then verify it.
 * `selectedKeys` are DisclosableField.key values the holder opted to include.
 */
export async function discloseAndVerify(selectedKeys: string[]): Promise<DisclosureResult> {
  const pointers: string[] = [];
  for (const key of selectedKeys) {
    const field = DISCLOSABLE_FIELDS.find((f) => f.key === key);
    if (field) pointers.push(...field.pointers);
  }

  const derived = await deriveSd(SD_BASE, { selectivePointers: pointers, documentLoader: sdLoader });
  const result = await verifySd(derived, { documentLoader: sdLoader });
  return { derived, verified: result.verified, ...(result.error ? { error: result.error } : {}) };
}
